name: Release

on:
  push:
    branches:
      - main

jobs:
  check-formatting:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - run: yarn

      - run: yarn release
        env:
          GH_TOKEN: ${{ secrets.SEMANTIC_RELEASE_GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.SEMANTIC_RELEASE_NPM_TOKEN }}
